List<String> originalStrings = ["Explore Your Cycle",
  "Access educational resources and valuable content for a healthier menstrual journey.",
  "Your Personal Guide",
  "Meet Paddy, Your Personal Chatbot Companion - ask questions freely, keep secrets private, and get personalized advice.", //changed
  "Empower Change Through Donation and Engagement", //changed
  "Support Causes, Share Stories, and Connect with Like-minded Individuals", //changed
  'Menstrual Hygiene',
  "E-Mail",
  "Password",
  "Remember me",
  "Forgot Password?",
  "Sign In",
  "Create Account",
  "Connect with Period",
  "Join our community for personalized menstrual health support and resources.",
  "Or Sign In with",
  "Skip",
  "Enter your email to receive instructions on resetting your password and regain access to Period.",
  "Submit",
  "Password Reset Email Sent",
  "Your account security is our priority! We've sent you a secure link to safely change your password and keep your account protected.",
  "Done",
  "Resend Email",
  "First Name",
  "Last Name",
  "Username",
  "Phone No.",
  "Create account", //changed
  "or sign up with",
  "Verify your email address",
  "Confirm your email address to unlock full access to Period's menstrual health resources.",
  "Your email has been successfully verified. Enjoy full access to menstrual health resources and community support.",
  "Continue",
  "Resend Email",
  "Type message",
  "Categories",
  'Organiser',
  'Campaigns',
  "Events",
  "Search Organizations",
  'Beginners guide to menstrual health',
  'Featured Videos',
  'Latest Articles',
  'Course Details',
  'Introduction',
  'What is menopause',
  'What do women have discomfort?',
  'Change profile picture',
  'Profile Information',
  'Name',
  'Personal Information',
  'Date of Birth',
  "Account",
  'Account Settings',
  "Bookmarked Resources",
  "My Donations",
  "My Blogs",
  "Favorite Campaigns",
  "Saved Blogs",
  "Track your contributions",
  "Your experiences at one place",
  "Stay connected to causes close to your heart",
  "Your favorite reads",
  "Explore your saved educational treasures",
  'App Settings',
  "Change language",
  "Tailor your experience with a language switch",
  "Welcome to Period!",
  "What are periods?"
];