List<String> originalStrings = ["Explora Tu Ciclo",
  "Accede a recursos educativos y contenido valioso para un viaje menstrual más saludable.",
  "Tu Guía Personal",
  "Soporte de chatbot: haz preguntas libremente, guarda secretos en privado y recibe consejos personalizados.",
  "Curado para Ti",
  "Descubre una gama de productos menstruales que se adaptan a tu comodidad y bienestar.",
  "Higiene Menstrual",
  "Correo Electrónico",
  "Contraseña",
  "Recuérdame",
  "¿Olvidaste tu Contraseña?",
  "Iniciar Sesión",
  "Crear Cuenta",
  "Conectar con el Período",
  "Únete a nuestra comunidad para obtener apoyo y recursos personalizados para la salud menstrual.",
  "O Inicia Sesión con",
  "Saltar",
  "Ingresa tu correo electrónico para recibir instrucciones sobre cómo restablecer tu contraseña y recuperar el acceso a Período.",
  "Enviar",
  "Correo Electrónico de Restablecimiento de Contraseña Enviado",
  "¡La seguridad de tu cuenta es nuestra prioridad! Te hemos enviado un enlace seguro para cambiar tu contraseña y mantener protegida tu cuenta.",
  "Listo",
  "Reenviar Correo Electrónico",
  "Nombre",
  "Apellido",
  "Nombre de Usuario",
  "Número de Teléfono",
  "Creemos tu cuenta",
  "o Regístrate con",
  "Verifica tu dirección de correo electrónico",
  "Confirma tu dirección de correo electrónico para desbloquear el acceso completo a los recursos de salud menstrual de Período.",
  "Tu correo electrónico ha sido verificado exitosamente. Disfruta del acceso completo a los recursos de salud menstrual y el apoyo de la comunidad.",
  "Continuar",
  "Reenviar Correo Electrónico",
  "Escribe un mensaje",
  "Categorías",
  "Organizador",
  "Campañas",
  "Eventos",
  "Buscar Organizaciones",
  "Guía para Principiantes sobre la Salud Menstrual",
  "Videos Destacados",
  "Últimos Artículos",
  "Detalles del Curso",
  "Introducción",
  "¿Qué es la Menopausia?",
  "¿Por qué las mujeres tienen molestias?",
  "Cambiar foto de perfil",
  "Información del Perfil",
  "Nombre",
  "Información Personal",
  "Fecha de Nacimiento",
  "Cuenta",
  "Configuración de la Cuenta",
  "Recursos Marcados",
  "Mis Donaciones",
  "Mis Blogs",
  "Campañas Favoritas",
  "Blogs Guardados",
  "Rastrea tus contribuciones",
  "Tus experiencias en un solo lugar",
  "Mantente conectado a las causas que te importan",
  "Tus lecturas favoritas",
  "Explora tus tesoros educativos guardados",
  "Configuración de la Aplicación",
  "Cambiar idioma",
  "Personaliza tu experiencia con un cambio de idioma",
  "¡Bienvenido a Período!",
  "¿Qué son los períodos?"
];
