List<String> originalStrings = ["Erforschen Sie Ihren Zyklus",
  "Zugang zu Bildungsressourcen und wertvollem Inhalt für eine gesündere Menstruationsreise.",
  "Ihr persönlicher Leitfaden",
  "Chatbot-Unterstützung – Stellen Sie frei Fragen, halten Sie Geheimnisse privat und erhalten Sie persönliche Ratschläge.",
  "Zusammengestellt für Sie",
  "Entdecken Sie eine Auswahl an Menstruationsprodukten, die Ihrem Komfort und Wohlbefinden dienen.",
  "Menstruationshygiene",
  "E-Mail",
  "Passwort",
  "Erinnere mich",
  "Passwort vergessen?",
  "Anmelden",
  "Konto erstellen",
  "Verbinden Sie sich mit Periode",
  "Tritt unserer Community bei für persönliche Unterstützung und Ressourcen zur Menstruationsgesundheit.",
  "Oder anmelden mit",
  "Überspringen",
  "Geben Sie Ihre E-Mail-Adresse ein, um Anweisungen zum Zurücksetzen Ihres Passworts zu erhalten und wieder Zugriff auf Periode zu erhalten.",
  "Einreichen",
  "E-Mail zum Zurücksetzen des Passworts gesendet",
  "Ihre Kontosicherheit hat für uns oberste Priorität! Wir haben Ihnen einen sicheren Link gesendet, um Ihr Passwort sicher zu ändern und Ihr Konto zu schützen.",
  "Fertig",
  "E-Mail erneut senden",
  "Vorname",
  "Nachname",
  "Nutzername",
  "Telefonnummer",
  "Lassen Sie uns Ihr Konto erstellen",
  "oder registrieren Sie sich mit",
  "Bestätigen Sie Ihre E-Mail-Adresse",
  "Bestätigen Sie Ihre E-Mail-Adresse, um vollen Zugriff auf die Menstruationsgesundheitsressourcen von Periode zu erhalten.",
  "Ihre E-Mail wurde erfolgreich verifiziert. Genießen Sie vollen Zugriff auf Menstruationsgesundheitsressourcen und Community-Unterstützung.",
  "Fortsetzen",
  "E-Mail erneut senden",
  "Nachricht eingeben",
  "Kategorien",
  "Organisator",
  "Kampagnen",
  "Veranstaltungen",
  "Organisationen suchen",
  "Anfängerleitfaden zur Menstruationsgesundheit",
  "Ausgewählte Videos",
  "Neueste Artikel",
  "Kursdetails",
  "Einführung",
  "Was ist Menopause",
  "Was haben Frauen für Beschwerden?",
  "Profilbild ändern",
  "Profilinformationen",
  "Name",
  "Persönliche Informationen",
  "Geburtsdatum",
  "Konto",
  "Kontoeinstellungen",
  "Gespeicherte Ressourcen",
  "Meine Spenden",
  "Meine Blogs",
  "Lieblingskampagnen",
  "Gespeicherte Blogs",
  "Verfolgen Sie Ihre Beiträge",
  "Ihre Erfahrungen an einem Ort",
  "In Verbindung bleiben mit Herzensangelegenheiten",
  "Ihre Lieblingslektüre",
  "Erkunden Sie Ihre gespeicherten Bildungsschätze",
  "App-Einstellungen",
  "Sprache ändern",
  "Passe deine Erfahrung mit einem Sprachwechsel an",
  "Willkommen bei Periode!",
  "Was sind Perioden?"
];
