List<String> originalStrings = ["Explorar seu ciclo",
  "Acesse recursos educacionais e conteúdo valioso para uma jornada menstrual mais saudável.",
  "Seu Guia Pessoal",
  "Suporte de chatbot - faça perguntas livremente, mantenha segredos privados e obtenha conselhos personalizados.",
  "Curado para Você",
  "Descubra uma variedade de produtos menstruais que atendem ao seu conforto e bem-estar.",
  "Higiene menstrual",
  "E-mail",
  "Senha",
  "Lembrar-me",
  "Esqueceu a senha?",
  "Entrar",
  "Criar Conta",
  "Conecte-se com o Período",
  "Junte-se à nossa comunidade para suporte e recursos personalizados de saúde menstrual.",
  "Ou entrar com",
  "Pular",
  "Digite seu e-mail para receber instruções sobre como redefinir sua senha e recuperar o acesso ao Período.",
  "Enviar",
  "E-mail de redefinição de senha enviado",
  "A segurança da sua conta é nossa prioridade! Enviamos a você um link seguro para alterar sua senha com segurança e proteger sua conta.",
  "Concluído",
  "Reenviar E-mail",
  "Primeiro Nome",
  "Sobrenome",
  "Nome de Usuário",
  "Telefone",
  "Vamos criar sua conta",
  "ou inscreva-se com",
  "Verifique seu endereço de e-mail",
  "Confirme seu endereço de e-mail para desbloquear o acesso total aos recursos de saúde menstrual do Período.",
  "Seu e-mail foi verificado com sucesso. Aproveite o acesso total aos recursos de saúde menstrual e ao suporte da comunidade.",
  "Continuar",
  "Reenviar E-mail",
  "Digite a mensagem",
  "Categorias",
  "Organizador",
  "Campanhas",
  "Eventos",
  "Pesquisar Organizações",
  "Guia para Iniciantes de Saúde Menstrual",
  "Vídeos em Destaque",
  "Últimos Artigos",
  "Detalhes do Curso",
  "Introdução",
  "O que é menopausa",
  "Por que as mulheres sentem desconforto?",
  "Alterar foto do perfil",
  "Informações do Perfil",
  "Nome",
  "Informações Pessoais",
  "Data de Nascimento",
  "Conta",
  "Configurações da Conta",
  "Recursos Favoritos",
  "Minhas Doações",
  "Meus Blogs",
  "Campanhas Favoritas",
  "Blogs Salvos",
  "Acompanhe suas contribuições",
  "Suas experiências em um só lugar",
  "Permaneça conectado às causas que lhe são caras",
  "Suas leituras favoritas",
  "Explore seus tesouros educacionais salvos",
  "Configurações do Aplicativo",
  "Alterar Idioma",
  "Personalize sua experiência com uma troca de idioma",
  "Bem-vindo ao Período!",
  "O que são períodos?"
];
