List<String> originalStrings = ["Explorer votre cycle",
  "Accédez à des ressources éducatives et à un contenu précieux pour un voyage menstruel plus sain.",
  "Votre guide personnel",
  "Support du chatbot - posez librement des questions, gardez vos secrets privés et obtenez des conseils personnalisés.",
  "Sélectionné pour vous",
  "Découvrez une gamme de produits menstruels adaptés à votre confort et à votre bien-être.",
  "Hygiène menstruelle",
  "E-mail",
  "Mot de passe",
  "Souviens-toi de moi",
  "Mot de passe oublié?",
  "Se connecter",
  "Créer un compte",
  "Connectez-vous avec Période",
  "Rejoignez notre communauté pour un soutien personnalisé en matière de santé menstruelle et des ressources.",
  "Ou se connecter avec",
  "Sauter",
  "Entrez votre adresse e-mail pour recevoir des instructions de réinitialisation de votre mot de passe et retrouver l'accès à Période.",
  "Soumettre",
  "E-mail de réinitialisation de mot de passe envoyé",
  "La sécurité de votre compte est notre priorité! Nous vous avons envoyé un lien sécurisé pour modifier votre mot de passe en toute sécurité et protéger votre compte.",
  "Terminé",
  "Renvoyer l'e-mail",
  "Prénom",
  "Nom de famille",
  "Nom d'utilisateur",
  "Numéro de téléphone",
  "Créons votre compte",
  "ou inscrivez-vous avec",
  "Vérifiez votre adresse e-mail",
  "Confirmez votre adresse e-mail pour débloquer l'accès complet aux ressources de santé menstruelle de Période.",
  "Votre adresse e-mail a été vérifiée avec succès. Profitez d'un accès complet aux ressources de santé menstruelle et au soutien de la communauté.",
  "Continuer",
  "Renvoyer l'e-mail",
  "Taper un message",
  "Catégories",
  "Organisateur",
  "Campagnes",
  "Événements",
  "Rechercher des organisations",
  "Guide du débutant pour la santé menstruelle",
  "Vidéos en vedette",
  "Derniers articles",
  "Détails du cours",
  "Introduction",
  "Qu'est-ce que la ménopause",
  "Qu'est-ce que les femmes ont comme inconfort?",
  "Changer d'image de profil",
  "Informations de profil",
  "Nom",
  "Informations personnelles",
  "Date de naissance",
  "Compte",
  "Paramètres du compte",
  "Ressources favorisées",
  "Mes dons",
  "Mes blogs",
  "Campagnes préférées",
  "Blogs enregistrés",
  "Suivez vos contributions",
  "Vos expériences en un seul endroit",
  "Rester connecté aux causes qui vous tiennent à cœur",
  "Vos lectures préférées",
  "Explorez vos trésors éducatifs enregistrés",
  "Paramètres de l'application",
  "Changer de langue",
  "Adaptez votre expérience avec un changement de langue",
  "Bienvenue à Période!",
  "Qu'est-ce que les règles ?"
];
